# Generated by Django 4.2.1 on 2024-01-22 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0078_pasttriperror_exceptiontext_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drivershiftdocket',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='drivershiftdocket',
            name='blowBack',
            field=models.CharField(default='', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='drivershiftdocket',
            name='callOut',
            field=models.CharField(default='', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='drivershiftdocket',
            name='truckConnectionId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocket',
            name='shiftDate',
            field=models.DateField(default=datetime.datetime(2024, 1, 22, 14, 34, 43, 852590), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='drivershiftdocket',
            unique_together={('docketNumber', 'shiftDate', 'clientId', 'truckConnectionId')},
        ),
    ]
